# Generated by Django 4.1.1 on 2022-11-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dato',
        ),
    ]
