# Generated by Django 4.1.1 on 2022-09-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0002_dato_x4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='x2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
