# Generated by Django 4.1.1 on 2022-09-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0003_alter_dato_x2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='x2',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
    ]
