# Generated by Django 4.1.1 on 2022-09-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0004_alter_dato_x2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='x5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
