# Generated by Django 4.1.1 on 2022-09-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0005_dato_x5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato',
            name='x5',
        ),
    ]
